### ISSUE TITLE
API: POST /blockchain_entry route often returns empty data for valid transactions

### ISSUE THREAD

**Issue by DaMatrix** [AIBlockOfficial/Network#59]
An example, querying four transactions by hash:

```
curl -X POST -k -H 'Content-Type: application/json' -i 'https://storage.aiblock.dev/blockchain_entry' --data '[
  "g12b2f321e1f52c57da66e65bd4be9c5",
  "gbcb096995b7d02fee4af7bdfc452220",
  "g52868967a234ca5b52e99a281a2b1ab",
  "g23fedfea1cc5e0e77c3cab541b6e4b5"
]'
```

Gives me the following result:
```
{
  "id": "",
  "status": "Success",
  "reason": "Database item(s) successfully retrieved",
  "route": "blockchain_entry",
  "content":[
    ["","",""],
    ["gbcb096995b7d02fee4af7bdfc452220",{"inputs":[{"previous_out":null,"script_signature":{"stack":[{"Num":3}]}}],"outputs":[{"value":{"Token":2590244360},"locktime":103,"script_public_key":"c0537dae4e2d8ab6722d835878fda785391ebdb4118785c249c44185c9039f1b"}],"version":6,"fees":[],"druid_info":null},{"Tx":{"block_num":3,"tx_num":0}}],
    ["","",""],
    ["","",""]
  ]
}
```

As you can see, 3/4 of the transactions simply return `["","",""]`, even though they're valid transactions which show up on the block explorer:

- Failing transactions:
  - [g12b2f321e1f52c57da66e65bd4be9c5](https://explorer.aiblock.ch/transaction/g12b2f321e1f52c57da66e65bd4be9c5)
  - [g52868967a234ca5b52e99a281a2b1ab](https://explorer.aiblock.ch/transaction/g52868967a234ca5b52e99a281a2b1ab)
  - [g23fedfea1cc5e0e77c3cab541b6e4b5](https://explorer.aiblock.ch/transaction/g23fedfea1cc5e0e77c3cab541b6e4b5)
- Successful transaction:
  - [gbcb096995b7d02fee4af7bdfc452220](https://explorer.aiblock.ch/transaction/gbcb096995b7d02fee4af7bdfc452220)

In fact, the overwhelming majority of transactions I've tried seem to fail in this way. I'm not sure if this is user error or not, but if I am doing something wrong, some kind of meaningful error message would be nice rather than simply getting an empty string back.

**Comment by BHouwens** [comment]
The failing transactions are on the mainnet, you're querying the testnet in this call

**Comment by DaMatrix** [comment]
Ah, didn't realize that! Changing the URL to `https://storage.aiblock.ch/blockchain_entry` fixes it.

That said, it *is* strange that the transactions show up with the block explorer set to MAINNET, but that seems to be a separate issue.

![image](https://github.com/AIBlockOfficial/Network/assets/11216106/043b6c8a-d85b-4988-99be-70082714b86c)
